### PR TITLE
slc: rewrite usage message

### PR DESCRIPTION
**Pull request by sam-github**
Clarify the role and purpose of commands, and remove use of the man page
formatter.

Intention is to highlight the main tooling, moving internal and deprecated commands out of prominence (though still documented and supported).

You can see new slc usage in the [README](https://github.com/strongloop/strongloop/blob/feature/cli-cleanup/README.md#usage) and the original [text](https://github.com/strongloop/strongloop/blob/feature/cli-cleanup/man/slc.txt).

Connected to strongloop-internal/scrum-nodeops#273

### CODE REVIEW

**Comment by sam-github** [comment]
I can also add in the strongloop README links to all its dependencies, so its easy to click through to the READMEs for them (and those READMEs have the usage, so its a fast way of seeing the usage of the entire slc without running it).

**Comment by chandadharap** [comment]
I read through this, and this is not quite there as far as simplicity. This is why we had the docs.sl link earlier. But Let me get back in a day or so. 

My feelings are this is still in the vein of "list everything we have". 

So one thing to think about, check out how npm does its docs https://github.com/npm/npm   and.. also ummmmm pm2.

**Comment by sam-github** [comment]
@chandadharap this PR rewrites the slc ***usage*** message (what you get from `slc --help`).

Please don't be side-tracked by the fact that the usage message shows up in the README, it wasn't an attempt to rework the README substantially, I just did that because every other strongloop module with a CLI has a copy of the CLI --help output in the README, it seemed weird that strongloop's README did not. But slc may be a bit different, I can take it out if you'd like.

If you think that  the [new usage message](https://github.com/strongloop/strongloop/blob/feature/cli-cleanup/man/slc.txt) is an improvement of over the [old one](https://github.com/strongloop/strongloop/blob/73b3ed1a16892ce4af6d0edeaad687b66e41b83c/man/slc.md) I'd like to merge this. Or if you have suggestions on the text in the new usage message, I can improve it.

WRT. a new README, I suggest we should do it in another issue, it will take a lot more time.

npm docs are not a useful model, they are 80% instructions for how to install/uninstall npm (despite that nobody does that, they use the npm that came from node).

pm2's README is like loopback.io, its a pretty set of screenshots with marketing blurbs beside.

I really, really think we should have such a page for nodeops, either in strongloop/README, or at nodeops.io, or both, but its beyond my marketing chops to build such a thing in an hour or two. Or maybe at all. I could help brainstorm the features that should be on it, though.

**Comment by chandadharap** [comment]
Agree to new usage message.
@ijroth to provide blurb for README, at end of which it should point back ot the docs.

**Comment by sam-github** [comment]
@ijroth send me any README changes you want anytime

**Pull request merged**
