### PR TITLE
Remove strongops command

### PR DESCRIPTION
**Pull request by sam-github**
connected to strongloop-internal/scrum-nodeops#796

### CODE REVIEW

**Comment by rmg** [comment]
:+1: x :100: 
:tada:

**Comment by sam-github** [comment]
TBD: https://github.com/strongloop/strong-pm/issues/183#issuecomment-95242688, add strong-mesh-models

**Comment by rmg** [comment]
Ah, I didn't notice the switch to tap at first.. I wonder if the failure on Windows is related.

**Comment by sam-github** [comment]
```
[sl-ci-run INFO  204.56 ]: Running tests...
[sl-ci-run INFO  204.56 ]: command: tap --bail --coverage --coverage-report=cobertura test/test-*.* > tests.tap
[sl-ci-run INFO  204.57 ]: env: TAP=true PATH=C:/jenkins/workspace/strongloop.pr/603c8e0e/node_modules/.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Python34\;C:\Ruby21-x64\bin\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.2 & MySQL Utilities 1.5.2 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.2 & MySQL Utilities 1.5.2 1.5\Doctrine extensions for PHP\;C:\ProgramFiles\phantomjs-1.9.7-windows\phantomjs-1.9.7-windows\;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:/jenkins/workspace/strongloop.pr/603c8e0e/node_modules/instantclient NODE_ENV=test DEBUG=

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn Unknown system errno 193
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
[sl-ci-run INFO  205.29 ]: Stripping ANSI escape codes from tests.tap...
'C:' is not recognized as an internal or external command,
operable program or batch file.
```

^--- I will rewrite test to not use nexpect, in retrospect, I'm not sure why it did.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
argh. didn't build the right commit :-(

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
