### PR TITLE
deps: hoist ws to reduce duplication (on hold)

### PR DESCRIPTION
**Pull request by rmg**
/cc @piscisaureus

### CODE REVIEW

**Comment by sam-github** [comment]
lgtm

**Comment by rmg** [comment]
I'm going to hold off on this until more things are using ws@0.7.1. node-inspector doesn't and strong-mesh-client uses engine.io, which uses ws but only engine.io#master uses ws@0.7.1... so currently this would not actually reduce the number of copies installed.

**Comment by rmg** [comment]
This is the current state of `ws` dependencies in strongloop:
```
│ ├─┬ ws@0.4.32
│ │ │ └─┬ ws@0.5.0
│ └─┬ ws@0.7.2
│ │ └─┬ ws@0.4.32
│ │ └─┬ ws@0.7.2
│ │ └─┬ ws@0.7.2
```

Related/blocking issues:
 - strongloop/strong-control-channel#21
   - removes one of the copies of ws@0.4.32
 - #231 
   - the latest node-inspector depends on ws@0.7 instead of ws@0.4 which would reduce duplication
 - Automattic/engine.io-client#388 and Automattic/engine.io#322
   - engine.io#master and engine.io-client#master have been updated to use ws@0.7, but the changes have not yet been published to npm
 - websockets/ws#508
   - ideally this would allow everyone to standardize on `^1.0.0` instead of being locked to `0.x.*` by `^0.x`

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
