### PR TITLE
[SEMVER-MAJOR] Remove lb-ng-doc to get rid of docular dependency

### PR DESCRIPTION
**Pull request by bajtos**
See also https://github.com/strongloop/loopback-sdk-angular-cli/pull/36

/to @rmg or @sam-github please review
/cc @chandadharap

### CODE REVIEW

**Comment by rmg** [comment]
Removing commands should trigger a semver-major for this package, so this PR should also bump the major in package.json I think.

**Comment by sam-github** [comment]
I agree with @rmg, this is a major bump of slc, otherwise, LGTM

**Comment by bajtos** [comment]
@rmg amended, LGTY now?

**Comment by rmg** [comment]
LGTM. :shipit:

**Pull request merged**
