### PR TITLE
Rename `slc pmctl` to `slc ctl`

### PR DESCRIPTION
**Pull request by sam-github**
Connect to strongloop-internal/scrum-nodeops#346

/to @chandadharap 
/cc @DeniseLee @crandmck

### CODE REVIEW

**Comment by sam-github** [comment]
@chandadharap this what we want?

Note that old name is still there, I'll remove it some time in the future.

**Comment by rmg** [comment]
@sam-github can you update the commit message to reflect that `slc pmctl` isn't removed? It looks like a bug in the commit as is. Should we make it print out a deprecation notice?

**Comment by sam-github** [comment]
/to @rmg I think people will forget it ever existed if we stop documenting it... and in 6 months we can delete it. I improved the commit message, ty.

**Comment by rmg** [comment]
@sam-github if one doesn't look at the docs and relies on `slc pmctl --help` instead, they will be in for a surprise when it is suddenly (to them) removed. I don't know about others, but `man` and `--help` tend to be the primary docs I read for CLIs. If you don't think it's a problem for `slc pmctl` users then I'm also fine with dealing with it if/when it comes up.

**Comment by sam-github** [comment]
`slc --help` no longer mentions pmctl, so soon the only people who will even know of its existence are the 5 or 10 pmctl users outside of strongloop, and strongloopers.

Nobody appeared to notice when I deleted `slc clusterctl`, as a point of reference. I'm not sure if anyone even remembers it was there. The changeover to everyone use `slc runctl` happened pretty quickly.

**Comment by sam-github** [comment]
See https://github.com/strongloop-internal/scrum-nodeops/issues/346#issuecomment-78003192

**Comment by chandadharap** [comment]
LGTM

**Comment by sam-github** [comment]
@crandmck This requires a doc change, I'm not sure if you have a story for it.

**Comment by crandmck** [comment]
> I'm not sure if you have a story for it.
Yes, we have https://github.com/strongloop-internal/scrum-nodeops/issues/365

**Pull request merged**
