### PR TITLE
Portable prepublish

### PR DESCRIPTION
**Pull request by rmg**
Allows dev/CI on Windows.

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github I've finally worked out the kinks with both Windows _and_ node 0.11.15-pre (using a custom build of node due to joyent/node#8962).

Can you take one last look before I merge?

**Comment by sam-github** [comment]
LGTM

**Pull request merged**
