### PR TITLE
Add liberty-pm server and collective commands

### PR DESCRIPTION
**Pull request by sam-github**
connected to https://github.com/strongloop-internal/scrum-nodeops/issues/1125

### CODE REVIEW

**Comment by pthieu** [comment]
LGTM

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@rmg I'm trying to figure out why this fails:

Multiple platforms say this:

- `npm WARN package.json strongloop@6.0.0 No bin file found at ./node_modules/loopback-sdk-angular-cli/bin/lb-ng` not sure where this is coming from... works for me locally, probably not an issue.

- `npm ERR! notarget No compatible version found: strong-liberty-pm@'>=0.0.0 <0.0.1'` but the dep spec is `^0.0.0`, and there are many matching: `... "0.0.135","0.0.136","0.0.137"]`

I suspect that what is happening is that strong-liberty-pm isn't found, so further dependencies are not installed, so eslint isn't found, at it all starts going bad quickly.

**Comment by sam-github** [comment]
Actually, I see, `^0.0.2` means exactly `=0.0.2` :-(  `0.0` is "extra special".

**Comment by rmg** [comment]
The warnings about `lb-ng` are because the bin doesn't exist at the given path until after those dependencies have been installed. Probably not a case that was considered when it was decided to add that warning so early in the install process.

**Comment by sam-github** [comment]
Not going to do.

**Pull request closed without merging**
