### PR TITLE
Lock sqlite version to fix global installation

### PR DESCRIPTION
**Pull request by dzonatan**
Quick PR to fix global installation #324

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by sam-github** [comment]
commit message needs a link to https://github.com/mapbox/node-sqlite3/issues/720, and a description of what problem is being solved, other than that, LGTM

**Comment by sam-github** [comment]
replaced by #326

**Comment by superkhau** [comment]
Closing in favour of #326. @dzonatan Thanks for the contribution. ;)

**Comment by SushobhitKhanna** [comment]
At what location is this file present where we need to do sqlite changes

**Pull request closed without merging**
