### PR TITLE
Upgrade Node Inspector

### PR DESCRIPTION
**Pull request by gunjpan**
node-inspector(~0.7.0 - 0.7.4 to be specific)
breaks slc debug. Changing it to 0.12.7 -
latest fixes the issue.
Connect to #301

### CODE REVIEW

**Comment by sam-github** [comment]
@gunjpan please spell check your commit message, get a review from Miroslav

**Comment by gunjpan** [comment]
@sam-github : Thanks for the comments, corrected. 
@bajtos : PTAL, thanks

**Comment by bajtos** [comment]
> Upgrade `slc debug` from Node Inspector 0.7 to Node Inspector 0.12

See the discussion in #185.

Node Inspector 0.7.x was the last version that did not have any native dependencies beyond `ws`. After that, Node Inspector underwent major refactoring that introduced additional native dependencies and started injecting code into the debugged process (e.g. a websocket server allowing Node Inspector to invoke v8 features like heap dump).

Honestly, I stopped following Node Inspector development long long time ago and I don't have any idea how stable the latest version is and whether it (or its native dependencies) support all Node versions that `slc` should support.

To keep my comment constructive. I think we should test the latest Node Inspector and make sure it works good enough on all platforms we support before landing the upgrade.

@sam-github @chandadharap thoughts?

**Comment by sam-github** [comment]
I think testing is reasonable, @chandadharap @cgole

**Comment by bajtos** [comment]
See https://github.com/strongloop-internal/scrum-nodeops/issues/1475 for test results.

**Comment by bajtos** [comment]
The code change is fine with me, we need to decide whether the two bugs described in https://github.com/strongloop-internal/scrum-nodeops/issues/1475#issuecomment-224296939 are acceptable or not.

**Comment by rmg** [comment]
How do we feel about this, given than https://github.com/nodejs/node-inspect is now a thing?

**Comment by rmg** [comment]
Closing for now, since I suspect that this won't go forward and it can easily be resurrected.

**Pull request closed without merging**
