### PR TITLE
bin: fix lb-ng linking

### PR DESCRIPTION
**Pull request by forivall**
fixes strongloop/loopback#2714

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by heracek** [comment]
I verified this PR fixes the issue.
This works:
```
npm install -g strongloop@forivall/strongloop#fix-lb-ng
```

This fails due to strongloop/loopback#2714:
```
npm install -g strongloop
```

**Comment by davidcheung** [comment]
@slnode ok to test 
cc @bajtos

**Comment by bajtos** [comment]
LGTM, let's land this ASAP as CI passes.

**Comment by bajtos** [comment]
@forivall thank you for the pull request!
@heracek and thank you too for your help with verifying this patch.

**Comment by davidcheung** [comment]
@slnode test please

**Comment by agustinfrancesa** [comment]
@heracek it works for me too, I just removed /usr/local/bin/lb-ng and works on OSx 10.11.6

**Comment by davidcheung** [comment]
@slnode test please

**Comment by esvignolo** [comment]
@heracek it works for me too

**Comment by rmg** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@rmg PTAL

**Comment by rmg** [comment]
@forivall could you include in the commit message that `2.1.0` was the first release to include the `.js` version of the file?

I'm assuming that statement is true. If that is not the case, then there's no need to change the version specifier, in which case could you please revert that part of the commit.

**Comment by forivall** [comment]
@rmg Yup, I added the version specifier, since the .js version of the file was introduced in https://github.com/strongloop/loopback-sdk-angular-cli/commit/4a1b9b59d0fdbff89feeae3ab295dcaedab51fb1 , whose first release was `2.1.0`

**Comment by Tuxity** [comment]
Oh god, thank you it works.

**Comment by esvignolo** [comment]
Hi, anybode knows when will be published the solution? 
I using into heroku and i can't deploy because the push do "npm install -g strongloop" automatically on heroku server. (and now because this error, the build fail).

Thanks

**Comment by esvignolo** [comment]
Hi, anybode knows when will be published the solution? 
I using into heroku and i can't deploy because the push do "npm install -g strongloop" automatically on heroku server. (and now because this error, the build fail).

Thanks

**Comment by reichert621** [comment]
@bajtos @davidcheung looks like the CI checks have passed, can we get this merged ASAP?

**Comment by davidcheung** [comment]
Thanks @forivall and everyone! the fix has been published in https://github.com/strongloop/strongloop/commit/979a0458a3d3e7b365ce10e963ac5160629049a8 has been published

**Pull request merged**
